---
title: "Fig. 1 - Beta Diversity"
author: "Avril Metcalfe-Roach"
date: "`r Sys.Date()`"
output: html_document
---

```{r Make Plots}
library(sjPlot)
library(phyloseq)
library(tidyverse)
library(vegan)

# Load all datasets, filter fecal dataset to only include sac samples so that they match other locations
psi = readRDS('Data Files/MetaCyc_Ileum.rds') %>% subset_samples(Group != 'TPN_day_2')
psj = readRDS('Data Files/MetaCyc_Jejunum.rds') %>% subset_samples(Group != 'TPN_day_2')
psf = readRDS('Data Files/MetaCyc_Colon.rds') %>% subset_samples(Group != 'TPN_day_2' & Timing=='Sac')

# Change factors to characters so that they can be modified
psf@sam_data$Groups = as.character(psf@sam_data$Groups)
psi@sam_data$Groups = as.character(psi@sam_data$Groups)
psj@sam_data$Groups = as.character(psj@sam_data$Groups)

# Annotate the groups to be more descriptive
psf@sam_data$Groups[psf@sam_data$Day==0] = 'Baseline'
psf@sam_data$Groups[psf@sam_data$Day != 0 & psf@sam_data$TPN_control=='Control'] = 'Control'
```


```{r Centroids}
# Run beta diversity for all 3 datasets
plots = list()
for (L in list(psf,psi,psj)){
  
  # Annotate which tissue
  if(identical(L,psi)){tissue = 'Ileum'}
  if(identical(L,psj)){tissue = 'Jejunum'}
  if(identical(L,psf)){tissue = 'Colon'}

  # Make the labels nice
  L@sam_data$TPN_control = recode(L@sam_data$TPN_control, TPN='TPN Day 4/6',Control = 'Control/Baseline')
  
  # Rarefy to even depth:
  Rar_table <- rarefy_even_depth(L, sample.size = min(sample_sums(L)), rngseed = 1234) %>% suppressMessages()
  
  # Calculate beta diversity
  PS.ord <- ordinate(Rar_table, method = "PCoA",distance =  "bray")
  percentVar <- round(100 * PS.ord$values$Relative_eig, digits = 1) 
  
  # Plot beta diversity
  p = plot_ordination(Rar_table, PS.ord, type="samples", color="TPN_control") +
    coord_fixed() +
    ggtitle(tissue) +
    geom_point(size = 2) +
    stat_ellipse(size=1) +
    xlab(paste0("PC1: ", percentVar[1], "% variance")) + 
    ylab(paste0("PC2: ", percentVar[2], "% variance")) +
    theme_bw(base_size = 18) +
    ggeasy::easy_center_title()
    
  plots <<- append(plots, list(p))
}

# Combine the three plots
beta_c = ggpubr::ggarrange(plotlist = plots, common.legend = T, legend = 'none', ncol = 3, align = 'hv')

save_plot(filename = "Figures/Fig 4 - Beta Diversity.tif",
         fig = last_plot(),
         width = 30,
         height = 12,
         dpi = 300,
         theme = theme_get()
  )
```

```{r Centroid Statistics}
stats = list(psf,psi,psj) %>% 
  lapply(function(x){
    # x = psf
    # Same steps as above
    if(identical(x,psi)){tissue = 'Ileum'}
    if(identical(x,psj)){tissue = 'Jejunum'}
    if(identical(x,psf)){tissue = 'Colon'}
    x@sam_data$TPN_control = recode(x@sam_data$TPN_control, TPN='TPN Day 4/6',Control = 'Control/Baseline')
    Rar_table <- rarefy_even_depth(x, sample.size = min(sample_sums(x)), rngseed = 1234) %>% suppressMessages()
    
    #Across all groups:
    ps_bray <- phyloseq::distance(Rar_table, method = "bray")
    p = adonis2(ps_bray ~ sample_data(Rar_table)$TPN_control)$`Pr(>F)`[1]
    stat_table = tibble(Tissue = tissue, Variable = 'TPN D4&6 vs Baseline/Control', Test = 'PERMANOVA', 
                        Metric = 'Bray-Curtis', Pval = p)
    
    return(stat_table)
  }) %>% bind_rows()


write.csv(stats, 'Statistics/Fig 4 - Beta Diversity Statistics.csv', row.names=F)
```

```{r Dispersion}
# A permutation-based implementation of Tukey's test to test pairwise differences between groups' beta dispersion

# For each of the intestinal segments:
plots = list()
stats = list()
for(x in list(psf,psi,psj)){
  # x=psi
  x@sam_data$TPN_control = recode(x@sam_data$TPN_control, TPN='TPN Day 4/6',Control = 'Control/\nBaseline')
  
  # Rarefy to even depth:
  x <- rarefy_even_depth(x, sample.size = min(sample_sums(x)), rngseed = 1234) %>% suppressMessages()
  
  ps_bray <- phyloseq::distance(x, method = "bray")
  
  # Calculate dispersion using default settings
  disp <- betadisper(ps_bray, sample_data(x)$TPN_control,type='centroid')
  
  # Calculate pval
  stat = TukeyHSD(disp, which = 'group', ordered = FALSE, conf.level = 0.95)
  
  # Create df for plotting
  df = disp$distances %>% as_tibble() %>% 
    mutate(Group=sample_data(x)$TPN_control) %>% 
    rename(Distance_to_centroid = value)
  
  pval_loc = max(df$Distance_to_centroid)*1.1
  
  p <- ggplot(df, aes(x=Group, y=Distance_to_centroid, colour=Group)) + 
    geom_boxplot(outlier.shape=NA) +
    geom_jitter(height=0, width=0.2) +
    ylab("Distance to centroid") +
    xlab(NULL) +
    theme_bw(base_size=18) +
    theme(axis.text.x  = element_text(angle=0, hjust=1)) + 
    theme(#text = element_text(face = "bold", size = 13, color = "black"),
          #axis.text = element_text(face = "bold", size = 12, color = "black"),
          legend.title = element_blank(),
          #legend.text = element_text(face = "bold", size = 13, color = "black"),
          #strip.text = element_text(face = "bold", size = 13, color = "black"),
          axis.text.x = element_text(angle = 35, vjust = 1, hjust=1)) +
    scale_color_discrete(labels=c('Control/Baseline', 'TPN Day 4/6')) +
    annotate("text", x=1.5, y=pval_loc, label= paste0("p = ",round(stat$group[4],3)), size = 5)
  plots <<- append(plots, list(p))
  stats <<- append(stats, list(stat))
  
}

# Combine the three plots
beta_d = ggpubr::ggarrange(plotlist = plots, common.legend = T, legend = 'bottom', ncol = 3, align = 'hv')

# save_plot(filename = "Figures/Fig 4 - Beta Diversity Dispersion.tif",
#          fig = last_plot(),
#          width = 30,
#          height = 10,
#          dpi = 300,
#          theme = theme_get()
#   )
beta_d
```

